#pragma once
#include <StdInclude.h>
#include "UIControls.h"
#include "CustomDvars.h"

namespace CameraMenu
{
	static string GetCFG()
	{
		std::string cfg =
			"//CAMERA //GENERATED BY T6MVM. REQUIRES T6MVM TO BE LOADED.\n" +
			std::string("mvm_frozenCam ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_frozenCam) ? 1 : 0) + ";\n" +
			std::string("mvm_showMarkerInfo ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_showMarkerInfo) ? 1 : 0) + ";\n" +
			std::string("mvm_dollyCamOffsetPos ") + std::to_string(T6SDK::Dvars::GetVec3(CustomDvars::dvar_dollyCamOffsetPos).x) + " " + std::to_string(T6SDK::Dvars::GetVec3(CustomDvars::dvar_dollyCamOffsetPos).y) + " " + std::to_string(T6SDK::Dvars::GetVec3(CustomDvars::dvar_dollyCamOffsetPos).z) + ";\n" +
			std::string("mvm_dollyCamOffsetRot ") + std::to_string(T6SDK::Dvars::GetVec3(CustomDvars::dvar_dollyCamOffsetRot).x) + " " + std::to_string(T6SDK::Dvars::GetVec3(CustomDvars::dvar_dollyCamOffsetRot).y) + " " + std::to_string(T6SDK::Dvars::GetVec3(CustomDvars::dvar_dollyCamOffsetRot).z) + ";\n" +
			std::string("mvm_freeRoamSpeed ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_freeRoamSpeed)) + ";\n" +
			std::string("mvm_accelerationFactor ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_accelerationFactor)) + ";\n" +
			std::string("mvm_slowingFactor ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_slowingFactor)) + ";\n" +
			std::string("mvm_shake ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_shake) ? 1 : 0) + ";\n" +
			std::string("mvm_shakeSpeed ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_shakeSpeed)) + ";\n" +
			std::string("mvm_shakeAmount ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_shakeAmount)) + ";\n" +
			std::string("mvm_shakePosition ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_shakePosition)) + ";\n" +
			std::string("mvm_shakeRotation ") + std::to_string(T6SDK::Dvars::GetFloat(CustomDvars::dvar_shakeRotation)) + ";\n";
		return cfg;
	}
	static void Draw()
	{
		if (!*UIControls::MainCameraTabButton.isChecked)
			return;
		
		vec2_t coords0 = T6SDK::Drawing::GetGridCellCoords(8, 4);
		T6SDK::Drawing::DrawTextAbsolute("^9DOLLY CAMERA", coords0.x, coords0.y, 1.0f, T6SDK::Drawing::T_WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);

		UIControls::UI_FrozenCamera.Draw();
		UIControls::UI_ShowDollyCamInfo.Draw();
		UIControls::UI_DollyCamOffsetX.Draw();
		UIControls::UI_DollyCamOffsetY.Draw();
		UIControls::UI_DollyCamOffsetZ.Draw();
		UIControls::UI_DollyCamRotationOffsetX.Draw();
		UIControls::UI_DollyCamRotationOffsetY.Draw();
		UIControls::UI_DollyCamRotationOffsetZ.Draw();

		vec2_t coords1 = T6SDK::Drawing::GetGridCellCoords(8, 15);
		T6SDK::Drawing::DrawTextAbsolute("^9FREE CAMERA", coords1.x, coords1.y, 1.0f, T6SDK::Drawing::T_WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);

		UIControls::UI_FreeRoamSpeed.Draw();
		UIControls::UI_FreeRoamAcceleration.Draw();
		UIControls::UI_FreeRoamSlowing.Draw();

		vec2_t coords2 = T6SDK::Drawing::GetGridCellCoords(8, 21);
		T6SDK::Drawing::DrawTextAbsolute("^9T6SHAKE", coords2.x, coords2.y, 1.0f, T6SDK::Drawing::T_WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);

		UIControls::UI_Shake.Draw();
		UIControls::UI_ShakeSpeed.Draw(CustomDvars::dvar_shake->current.enabled);
		UIControls::UI_ShakeAmount.Draw(CustomDvars::dvar_shake->current.enabled);
		UIControls::UI_ShakePositionAmount.Draw(CustomDvars::dvar_shake->current.enabled);
		UIControls::UI_ShakeRotationAmount.Draw(CustomDvars::dvar_shake->current.enabled);

		UIControls::UI_ExportCampathButton.Draw(T6SDK::Addresses::DemoPlayback.Value()->DollyCamMarkerCount > 0);
		UIControls::UI_ImportCampathButton.Draw();
	}
	void ToggleFrozen(T6SDK::Drawing::UI_CheckBoxButton* control)
	{
		CustomDvars::dvar_frozenCam->modified = true;
	}
	static void Init()
	{
		UIControls::UI_FrozenCamera = T6SDK::Drawing::UI_CheckBoxButton("MODE: NORMAL", "MODE: FROZEN", 4, 5, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_frozenCam->current.enabled, (uintptr_t)&ToggleFrozen);
		UIControls::UI_FrozenCamera.ToolTip = "please suggest your description >~<";

		UIControls::UI_ShowDollyCamInfo = T6SDK::Drawing::UI_CheckBoxButton("SHOW CAMERA MARKER INFO OFF", "SHOW CAMERA MARKER INFO ON", 8, 5, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_showMarkerInfo->current.enabled, 0x00);
		UIControls::UI_ShowDollyCamInfo.ToolTip = "please suggest your description >~<";

		UIControls::UI_DollyCamOffsetX = T6SDK::Drawing::UI_Slider("DOLLYCAM OFFSET X", &CustomDvars::dvar_dollyCamOffsetPos->current.vector[0], 0.0f, -5000.0f, 5000.0f, 4, 8, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_DollyCamOffsetX.ToolTip = "Position offset to be applied to moving dolly camera.";
		UIControls::UI_DollyCamOffsetY = T6SDK::Drawing::UI_Slider("DOLLYCAM OFFSET Y", &CustomDvars::dvar_dollyCamOffsetPos->current.vector[1], 0.0f, -5000.0f, 5000.0f, 8, 8, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_DollyCamOffsetY.ToolTip = "Position offset to be applied to moving dolly camera.";
		UIControls::UI_DollyCamOffsetZ = T6SDK::Drawing::UI_Slider("DOLLYCAM OFFSET Z", &CustomDvars::dvar_dollyCamOffsetPos->current.vector[2], 0.0f, -5000.0f, 5000.0f, 12, 8, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_DollyCamOffsetZ.ToolTip = "Position offset to be applied to moving dolly camera.";

		UIControls::UI_DollyCamRotationOffsetX = T6SDK::Drawing::UI_Slider("DOLLYCAM OFFSET PITCH", &CustomDvars::dvar_dollyCamOffsetRot->current.vector[0], 0.0f, -360.0f, 360.0f, 4, 11, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_DollyCamRotationOffsetX.ToolTip = "Rotation offset to be applied to moving dolly camera.";
		UIControls::UI_DollyCamRotationOffsetY = T6SDK::Drawing::UI_Slider("DOLLYCAM OFFSET YAW", &CustomDvars::dvar_dollyCamOffsetRot->current.vector[1], 0.0f, -360.0f, 360.0f, 8, 11, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_DollyCamRotationOffsetY.ToolTip = "Rotation offset to be applied to moving dolly camera.";
		UIControls::UI_DollyCamRotationOffsetZ = T6SDK::Drawing::UI_Slider("DOLLYCAM OFFSET ROLL", &CustomDvars::dvar_dollyCamOffsetRot->current.vector[2], 0.0f, -360.0f, 360.0f, 12, 11, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_DollyCamRotationOffsetZ.ToolTip = "Rotation offset to be applied to moving dolly camera.";

		UIControls::UI_FreeRoamSpeed = T6SDK::Drawing::UI_Slider("FREE ROAM SPEED", &CustomDvars::dvar_freeRoamSpeed->current.value, 1.0f, 0.0f, 2.0f, 4, 16, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_FreeRoamSpeed.ToolTip = "Free camera speed.";
		UIControls::UI_FreeRoamAcceleration = T6SDK::Drawing::UI_Slider("FREE ROAM ACCELERATE TO", &CustomDvars::dvar_accelerationFactor->current.value, 2.0f, 0.0f, 10.0f, 8, 16, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_FreeRoamAcceleration.ToolTip = "Free camera speed to be set while pressing ^5SHIFT.";
		UIControls::UI_FreeRoamSlowing = T6SDK::Drawing::UI_Slider("FREE ROAM SLOW DOWN TO", &CustomDvars::dvar_slowingFactor->current.value, 0.25f, 0.0f, 10.0f, 12, 16, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_FreeRoamSlowing.ToolTip = "Free camera speed to be set while pressing ^5CTRL.";

		UIControls::UI_Shake = T6SDK::Drawing::UI_CheckBoxButton("CAMERA SHAKE OFF", "CAMERA SHAKE ON", 4, 21, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_shake->current.enabled, 0x00);
		UIControls::UI_Shake.ToolTip = "Dolly camera shake that was made for Dmitriy Norton but he used it only once or maybe twice :(";

		UIControls::UI_ShakeSpeed = T6SDK::Drawing::UI_Slider("CAMERA SHAKE SPEED", &CustomDvars::dvar_shakeSpeed->current.value, 1.0f, 0.0f, 10.0f, 4, 24, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_ShakeSpeed.ToolTip = "Dolly camera shake speed.";

		UIControls::UI_ShakeAmount = T6SDK::Drawing::UI_Slider("CAMERA SHAKE AMOUNT", &CustomDvars::dvar_shakeAmount->current.value, 1.0f, 0.0f, 10.0f, 8, 24, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_ShakeAmount.ToolTip = "Dolly camera overall shake amount.";

		UIControls::UI_ShakePositionAmount = T6SDK::Drawing::UI_Slider("CAMERA SHAKE POSITION AMOUNT", &CustomDvars::dvar_shakePosition->current.value, 1.0f, 0.0f, 10.0f, 4, 27, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_ShakePositionAmount.ToolTip = "Dolly camera position shake intensity.";

		UIControls::UI_ShakeRotationAmount = T6SDK::Drawing::UI_Slider("CAMERA SHAKE ROTATION AMOUNT", &CustomDvars::dvar_shakeRotation->current.value, 1.0f, 0.0f, 10.0f, 8, 27, T6SDK::Drawing::ORANGECOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_ShakeRotationAmount.ToolTip = "Dolly camera rotation shake intensity.";


	}
}