#pragma once
#include "UIControls.h"
#include "Streams.h"
#include "CustomDvars.h"
#include "Settings.h"
namespace StreamsMenu
{

	static vector<int> streamsAvailableFPS = { 50, 100, 200, 250, 500, 1000 };
	static int selectedFPS = 5;

	static string GetCFG()
	{
		std::string cfg =
			"//STREAMS //GENERATED BY T6MVM. REQUIRES T6MVM TO BE LOADED.\n" +
			std::string("mvm_streams ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_streams) ? 1 : 0) + ";\n" +
			std::string("mvm_streams_noFlash ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_streams_noFlash)) + ";\n" +
			//std::string("mvm_streams_directory ") + std::string(T6SDK::Dvars::GetString(CustomDvars::dvar_streams_directory)) + ";\n" +
			std::string("mvm_streams_fps ") + std::to_string(T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_fps)) + ";\n" +
			std::string("mvm_streams_avi ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_streams_avi) ? 1 : 0) + ";\n" +
			std::string("mvm_streams_JPG ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_streams_JPG) ? 1 : 0) + ";\n" +
			std::string("mvm_streams_tickStart ") + std::to_string(T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart)) + ";\n" +
			std::string("mvm_streams_tickEnd ") + std::to_string(T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd)) + ";\n" +
			std::string("mvm_streams_recordCam ") + std::to_string(T6SDK::Dvars::GetBool(CustomDvars::dvar_streams_recordCam) ? 1 : 0) + ";\n";
		return cfg;
	}

	void SetStartTick()
	{
		if (T6SDK::Addresses::Tick.Value() > T6SDK::Addresses::cg->Tick)
		{
			T6SDK::ConsoleLog::LogTagged(T6SDK::ConsoleLog::C_WARNING, true, "STREAMS", "Tick mismatch. Unable start tick.");
			T6SDK::Input::CloseBlankMenu();
			T6SDK::Theater::Demo_Error("TICK MISMATCH", "Seems some internal ticks do not match. Please skip back once and try again.");
			(*T6SDK::Dvars::DvarList::r_blur)->current.value = 0.0f;
			return;
		}
		int startTick = T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart);
		if (startTick == -1)
		{
			if (T6SDK::Addresses::cg->Tick > T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd) && T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd) != -1)
			{
				//T6SDK::Theater::Demo_Error("Unable to set start tick.", "We can't record backwards yet.");
				return;
			}
			T6SDK::Dvars::SetInt(CustomDvars::dvar_streams_tickStart, T6SDK::Addresses::cg->Tick);
			int tick = T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart);
			char buffer[256];
			sprintf(buffer, "Start: ^3%i ^7(%02i:%02i)", tick, tick / 60000, tick % 60000 / 1000);
			UIControls::UI_StreamsStartTickButton.Text = buffer;
		}
		else if(startTick > -1)
		{
			T6SDK::Dvars::SetInt(CustomDvars::dvar_streams_tickStart, -1);
			UIControls::UI_StreamsStartTickButton.Text = "Start tick is not set";
		}
	}
	void SetEndTick()
	{
		int endTick = T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd);
		if (endTick == -1)
		{
			if (T6SDK::Addresses::cg->Tick < T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart) && T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart) != -1)
			{
				//T6SDK::Theater::Demo_Error("Unable to set end tick.", "We can't record backwards yet.");
				return;
			}
			T6SDK::Dvars::SetInt(CustomDvars::dvar_streams_tickEnd, T6SDK::Addresses::cg->Tick);
			int tick = T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd);
			char buffer[256];
			sprintf(buffer, "End: ^3%i ^7(%02i:%02i)", tick, tick / 60000, tick % 60000 / 1000);
			UIControls::UI_StreamsEndTickButton.Text = buffer;
		}
		else if(endTick > -1)
		{
			T6SDK::Dvars::SetInt(CustomDvars::dvar_streams_tickEnd, -1);
			UIControls::UI_StreamsEndTickButton.Text = "End tick is not set";
		}
	}

	std::string selectedFolder{};
	void SetStreamsDirectory()
	{
		// Open the folder dialog
		if (T6SDK::InternalFunctions::OpenFolderDialog(selectedFolder)) 
		{
			//CustomDvars::dvar_streams_directory->current.string = selectedFolder.c_str();
			//T6SDK::ConsoleLog::LogTagged(T6SDK::ConsoleLog::C_DEBUG, false, "STREAMS", "Selected folder: %s", CustomDvars::dvar_streams_directory->current.string);
			T6SDK::ConsoleLog::LogTagged(T6SDK::ConsoleLog::C_DEBUG, false, "STREAMS", "Selected folder: %s", Settings::Settings::StreamsDirectory.c_str());
			//Saving directory to settings
			Settings::Settings::SetStreamsDirectory(selectedFolder);
		}
		else 
		{
			std::cerr << "No folder selected or an error occurred." << std::endl;
		}
	}

	static void Draw()
	{
		if (!*UIControls::StreamsTabButton.isChecked)
			return;
		bool streamsEnabled = T6SDK::Dvars::GetBool(CustomDvars::dvar_streams);
		UIControls::UI_ToggleStreamsCheckBox.Draw();

		if(Settings::Settings::StreamsDirectory.empty())
			UIControls::UI_StreamsDirectoryButton.Text = "Output directory is not set";
		else
		{
			char buffer[256];
			sprintf(buffer, "Output: ^3%s", Settings::Settings::StreamsDirectory.c_str());
			UIControls::UI_StreamsDirectoryButton.Text = buffer;
		}
		UIControls::UI_StreamsDirectoryButton.Draw(streamsEnabled);

		int starttick = T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart);
		if(starttick > -1)
		{
			char buffer0[256];
			sprintf(buffer0, "Start: ^3%i ^7(%02i:%02i)", starttick, starttick / 60000, starttick % 60000 / 1000);
			UIControls::UI_StreamsStartTickButton.Text = buffer0;
		}
		else
			UIControls::UI_StreamsStartTickButton.Text = "Start tick is not set";
		UIControls::UI_StreamsStartTickButton.Draw(streamsEnabled);



		int endtick = T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd);
		if (endtick > -1)
		{
			char buffer1[256];
			sprintf(buffer1, "End: ^3%i ^7(%02i:%02i)", endtick, endtick / 60000, endtick % 60000 / 1000);
			UIControls::UI_StreamsEndTickButton.Text = buffer1;
		}
		else
			UIControls::UI_StreamsEndTickButton.Text = "End tick is not set";
		UIControls::UI_StreamsEndTickButton.Draw(streamsEnabled);


		//Draw duration category text
		const char* durationCategoryText = "^9DURATION SETTINGS";
		if (starttick > -1 && endtick > -1)
		{
			int totalFrames = (T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickEnd) - T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_tickStart)) / (1000 / T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_fps));
			char buffer0[256];
			sprintf(buffer0, "^9DURATION SETTINGS(^3%i ^9frames to be captured)", totalFrames);
			durationCategoryText = buffer0;
		}
		vec2_t coords = T6SDK::Drawing::GetGridCellCoords(8, 8);
		T6SDK::Drawing::DrawTextAbsolute(durationCategoryText, coords.x, coords.y, 1.0f, T6SDK::Drawing::T_WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);
		//End draw duration category text
	
		//Draw misc settings category text
		vec2_t coords2 = T6SDK::Drawing::GetGridCellCoords(8, 13);
		T6SDK::Drawing::DrawTextAbsolute("^9MISC SETTINGS", coords2.x, coords2.y, 1.0f, T6SDK::Drawing::T_WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);
		//End draw misc settings category text

		UIControls::UI_StreamsJPGCheckBox.Draw(streamsEnabled && !T6SDK::Dvars::GetBool(CustomDvars::dvar_streams_avi));

		T6SDK::Dvars::SetInt(CustomDvars::dvar_streams_fps, streamsAvailableFPS[selectedFPS]);
		char buffer[100];
		sprintf(buffer, "FPS: %i", T6SDK::Dvars::GetInt(CustomDvars::dvar_streams_fps));
		UIControls::UI_StreamsFPSEnum.Text = buffer;
		UIControls::UI_StreamsFPSEnum.Draw(streamsEnabled);

		UIControls::UI_StreamsAVICheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsNoFlashCheckBox.Draw(streamsEnabled);
		UIControls::UI_RecordCamCheckBox.Draw(streamsEnabled);

		//Draw stream passes

		//vec4_t margin = { -15.0f, 10.0f, -10.0f, -5.0f };
		//T6SDK::Drawing::DrawRectAbsolute(12, 4, 15, 24, margin, T6SDK::Drawing::T_BLACKCOLOR, T6SDK::AnchorPoint::TopLeft, 0x00);

		vec2_t coords3 = T6SDK::Drawing::GetGridCellCoords(13, 5);
		T6SDK::Drawing::DrawTextAbsolute("^9PASSES", coords3.x, coords3.y, 1.0f, T6SDK::Drawing::T_WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);

		UIControls::UI_StreamsPass1CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass2CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass3CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass4CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass5CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass6CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass7CheckBox.Draw(streamsEnabled);
		UIControls::UI_StreamsPass8CheckBox.Draw(streamsEnabled);
		//UIControls::UI_StreamsPass9CheckBox.Draw(streamsEnabled);
		//UIControls::UI_StreamsPass10CheckBox.Draw(streamsEnabled);

		//UIControls::UI_StreamsPass1Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass2Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass3Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass4Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass5Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass6Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass7Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass8Preview.Draw(streamsEnabled);
		UIControls::UI_StreamsPass2Preview.sizeX = UIControls::UI_StreamsPass2Preview.sizeY =(float)UIControls::UI_StreamsPass2CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass2CheckBox.btnRect.top;
		UIControls::UI_StreamsPass3Preview.sizeX = UIControls::UI_StreamsPass3Preview.sizeY =(float)UIControls::UI_StreamsPass3CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass3CheckBox.btnRect.top;
		UIControls::UI_StreamsPass4Preview.sizeX = UIControls::UI_StreamsPass4Preview.sizeY =(float)UIControls::UI_StreamsPass4CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass4CheckBox.btnRect.top;
		UIControls::UI_StreamsPass5Preview.sizeX = UIControls::UI_StreamsPass5Preview.sizeY =(float)UIControls::UI_StreamsPass5CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass5CheckBox.btnRect.top;
		UIControls::UI_StreamsPass6Preview.sizeX = UIControls::UI_StreamsPass6Preview.sizeY =(float)UIControls::UI_StreamsPass6CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass6CheckBox.btnRect.top;
		UIControls::UI_StreamsPass7Preview.sizeX = UIControls::UI_StreamsPass7Preview.sizeY =(float)UIControls::UI_StreamsPass7CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass7CheckBox.btnRect.top;
		UIControls::UI_StreamsPass8Preview.sizeX = UIControls::UI_StreamsPass8Preview.sizeY =(float)UIControls::UI_StreamsPass8CheckBox.btnRect.bottom - (float)UIControls::UI_StreamsPass8CheckBox.btnRect.top;
		//UIControls::UI_StreamsPass9CheckBox.Draw(streamsEnabled);
		//UIControls::UI_StreamsPass10CheckBox.Draw(streamsEnabled);

	}
	void OnTheaterControlsDrawn()
	{
		if (T6SDK::Dvars::GetBool(CustomDvars::dvar_streams) && !Settings::Settings::StreamsDirectory.empty())
		{
			int enabledStreamsCount = 0;
			for (auto& stream : Streams::Streams)
			{
				if (stream->toggle->current.enabled)
					enabledStreamsCount++;
			}
			if (enabledStreamsCount > 0)
			{
				vec2_t coords = T6SDK::Drawing::GetGridCellCoords(8, 19);
				char buffer[256];
				sprintf(buffer, "PRESS ^3%s ^7TO START RECORDING STREAMS", T6SDK::Input::GetKeyByCode(Settings::Settings::KeyBinds["StreamsStartStop"])->KeyName.c_str());
				T6SDK::Drawing::DrawTextAbsolute(buffer, coords.x, coords.y, 1.5f, T6SDK::Drawing::WHITECOLOR, T6SDK::AnchorPoint::Center, 0x00);
			}
		}
	}

	bool pass1PreviewState = false;
	bool pass2PreviewState = false;
	bool pass3PreviewState = false;
	bool pass4PreviewState = false;
	bool pass5PreviewState = false;
	bool pass6PreviewState = false;
	bool pass7PreviewState = false;
	bool pass8PreviewState = false;
	bool pass9PreviewState = false;
	bool pass10PreviewState = false;

	static void DisableStreamsPreviews(int pass = -1, bool* state = 0x00)
	{
		for(auto& stream : Streams::Streams)
		{
			stream->Disable();
		}
		if(pass > -1)
		{
			Streams::Streams[pass]->Enable();
			pass1PreviewState = false;
			pass2PreviewState = false;
			pass3PreviewState = false;
			pass4PreviewState = false;
			pass5PreviewState = false;
			pass6PreviewState = false;
			pass7PreviewState = false;
			pass8PreviewState = false;
			pass9PreviewState = false;
			pass10PreviewState = false;
		}
		if(state)
		{
			*state = true;
		}
	}

	static void Init()
	{
		UIControls::UI_ToggleStreamsCheckBox = T6SDK::Drawing::UI_CheckBoxButton("STREAMS OFF","STREAMS ON",4,5, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_streams->current.enabled, 0x00);
		UIControls::UI_ToggleStreamsCheckBox.ToolTip = "Toggle recording streams.";

		UIControls::UI_StreamsStartTickButton = T6SDK::Drawing::UI_ClickableButton("Start tick is not set", 4, 9, T6SDK::AnchorPoint::TopLeft, (uintptr_t)&SetStartTick);
		UIControls::UI_StreamsStartTickButton.ToolTip = "Tick value at which streams recording starts.";

		UIControls::UI_StreamsEndTickButton = T6SDK::Drawing::UI_ClickableButton("End tick is not set", 4, 11, T6SDK::AnchorPoint::TopLeft, (uintptr_t)&SetEndTick);
		UIControls::UI_StreamsEndTickButton.ToolTip = "Tick value at which streams recording stops.";

		UIControls::UI_StreamsFPSEnum = T6SDK::Drawing::UI_EnumButton("FPS: ", 0, 5, &selectedFPS, 4, 14, T6SDK::AnchorPoint::TopLeft, 0x00);
		UIControls::UI_StreamsFPSEnum.ToolTip = "Choose the desired FPS for the streams recording.";

		UIControls::UI_StreamsJPGCheckBox = T6SDK::Drawing::UI_CheckBoxButton("IMAGE FORMAT: PNG", "IMAGE FORMAT: JPG", 4, 16, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_streams_JPG->current.enabled, 0x00);
		UIControls::UI_StreamsJPGCheckBox.ToolTip = "^7Switch between ^5PNG ^7and ^5JPG ^7formats. PNG provides better quality. JPG takes less space.";

		UIControls::UI_StreamsAVICheckBox = T6SDK::Drawing::UI_CheckBoxButton("TYPE: IMAGE SEQUENCE", "TYPE: AVI", 4, 18, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_streams_avi->current.enabled, 0x00);
		UIControls::UI_StreamsAVICheckBox.ToolTip = "^2NOT IMPLEMENTED YET";

		UIControls::UI_StreamsNoFlashCheckBox = T6SDK::Drawing::UI_CheckBoxButton("NO FLASH OFF", "NO FLASH ON", 4, 20, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_streams_noFlash->current.enabled, 0x00);
		UIControls::UI_StreamsNoFlashCheckBox.ToolTip = "Don't want to see you screen flashing during recording each pass? Turn this on!";

		UIControls::UI_RecordCamCheckBox = T6SDK::Drawing::UI_CheckBoxButton("RECORD CAMERA DATA\tOFF", "RECORD CAMERA DATA\tON", 4, 22, T6SDK::AnchorPoint::TopLeft, &CustomDvars::dvar_streams_recordCam->current.enabled, 0x00);
		UIControls::UI_RecordCamCheckBox.ToolTip = "^2NOT IMPLEMENTED YET";//"Get camera orientation and position data exported for each recorded frame.";

		UIControls::UI_StreamsDirectoryButton = T6SDK::Drawing::UI_ClickableButton("Directory is not set", 4, 30, T6SDK::AnchorPoint::TopLeft, (uintptr_t)&SetStreamsDirectory);
		UIControls::UI_StreamsDirectoryButton.ToolTip = "Select the directory where the streams will be saved.";

		std::string uncheckedMaterial("menu_mp_lobby_views");
		std::string checkedMaterial("menu_mp_lobby_views");
		float scale = 1.5f / 1080.0f * static_cast<float>(T6SDK::Addresses::ScreenHeight.Value()); //Assuming that initial size is in 1920x1080	
		float sizeX = 33.0f * scale;
		float sizeY = 33.0f * scale;

		UIControls::UI_StreamsPass2Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 8, T6SDK::AnchorPoint::TopLeft, &pass2PreviewState, [](bool e) { e ? DisableStreamsPreviews(1,  &pass2PreviewState) : DisableStreamsPreviews(-1); });
		UIControls::UI_StreamsPass3Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 10, T6SDK::AnchorPoint::TopLeft, &pass3PreviewState, [](bool e) { e ? DisableStreamsPreviews(2, &pass3PreviewState) : DisableStreamsPreviews(-1); });
		UIControls::UI_StreamsPass4Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 12, T6SDK::AnchorPoint::TopLeft, &pass4PreviewState, [](bool e) { e ? DisableStreamsPreviews(3, &pass4PreviewState) : DisableStreamsPreviews(-1); });
		UIControls::UI_StreamsPass5Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 14, T6SDK::AnchorPoint::TopLeft, &pass5PreviewState, [](bool e) { e ? DisableStreamsPreviews(4, &pass5PreviewState) : DisableStreamsPreviews(-1); });
		UIControls::UI_StreamsPass6Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 16, T6SDK::AnchorPoint::TopLeft, &pass6PreviewState, [](bool e) { e ? DisableStreamsPreviews(5, &pass6PreviewState) : DisableStreamsPreviews(-1); });
		UIControls::UI_StreamsPass7Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 18, T6SDK::AnchorPoint::TopLeft, &pass7PreviewState, [](bool e) { e ? DisableStreamsPreviews(6, &pass7PreviewState) : DisableStreamsPreviews(-1); });
		UIControls::UI_StreamsPass8Preview = T6SDK::Drawing::UI_IconCheckBoxButton(uncheckedMaterial, checkedMaterial, sizeX, sizeY, 11, 20, T6SDK::AnchorPoint::TopLeft, &pass8PreviewState, [](bool e) { e ? DisableStreamsPreviews(7, &pass8PreviewState) : DisableStreamsPreviews(-1); });


		UIControls::UI_StreamsPass1Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass2Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass3Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass4Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass5Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass6Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass7Preview.ToolTip = "Click to preview!";
		UIControls::UI_StreamsPass8Preview.ToolTip = "Click to preview!";


		T6SDK::Events::RegisterListener(T6SDK::EventType::OnTheaterControlsDrawn, (uintptr_t)&OnTheaterControlsDrawn);
		//UIControls::UI_StreamsPass9CheckBox{};
		//UIControls::UI_StreamsPass10CheckBox{};
	}
}